### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by matthiasg** [mennovanslooten/Scout#1]
ScoutJS is not working on Windows. The bin script is not a usual nodejs bin script which just references  the entry file. Its a full bash script which wont work. 

When using the index.js directly its complaining about missing module `system`.

When installing system manually (`npm i system`) its complaining:

```
E:\Test\scoutjs\node_modules\scoutjs\lib\testreader.js:78
    var is_unreadable = !_fs.isReadable(full_path);
                             ^
TypeError: Object #<Object> has no method 'isReadable'
    at readFileOrDirectory (E:\Test\scoutjs\node_modules\scoutjs\lib\testreader.js:78:30)
    at E:\Test\scoutjs\node_modules\scoutjs\lib\testreader.js:110:9
    at Array.forEach (native)
    at Object.exports.readTestFiles (E:\Test\scoutjs\node_modules\scoutjs\lib\testreader.js:109:11)
    at Object.<anonymous> (E:\Test\scoutjs\node_modules\scoutjs\lib\testsuite.js:4:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Whats the story here ?

PS: Tested on Windows x64 with node `0.10.38`

**Comment by mennovanslooten** [comment]
The story is that I never tested it on windows. I'll see if I can make it work on my VM. Thanks so much for your feedback!

**Comment by Bigismall** [comment]
Scout is working on Windows  quite well if you use GitBash console.

**Comment by mennovanslooten** [comment]
@Bigismall Could you provide some details about how to make that work? I'd like to add that to the documentation.

**Comment by Bigismall** [comment]
of course, will write ASAP

**Comment by Bigismall** [comment]
Running SCOUT under Winodws is not complicated. What you need to have, is alternative console with bash interpreter.

You can use https://msysgit.github.io/ (contain: GIT+ Bash console) which has extremaly useful console, or http://win-bash.sourceforge.net

After you install one of above, the whole installation process looks like in http://mennovanslooten.github.io/Scout/getting_started.html,  with the difference of **Runing tests**

SCOUT uses bash interpreter, that's why you need run test in one of above mention consoles.
